### ISSUE TITLE
cannot filter compiler errors caused by missing methods

### ISSUE THREAD

**Issue by miwer106** [bendisposto/virtual-kata-lib#1] opened 2016-06-30 13:12 UTC
used class: CompilerResult
used method: getCompilerErrorsForCompilationUnit()
issue: 
starting the used method and trying to compile a test with an undeclared method, that you want to implement after testing, causes an error (you can find details and an example in the attachments) 

it would be good if you could check for compilation errors caused by a specified class or method, or get a class location if a method compilation error occurs

thanks!

![unbenannt](https://cloud.githubusercontent.com/assets/19970515/16489185/b5849c74-3ed4-11e6-853e-5cfe70dc4795.PNG)

**Comment by bendisposto** [comment] 2016-07-03 08:51
I am not 100% sure what is missing ?!?

**Comment by miwer106** [comment] 2016-07-03 10:08
Imagine you try and write a new method, that isn't yet implemented in the mainclass... 
you get an error because the compiler couldn't find the new method, which is absolutely right, 
but for us it's a problem, we're supposed to check for compilererrors, otherwise there would be no point in getting to the next phase (Make test fail - Make pass - Refactor) and that's where we would have to differentiate between compilererrors caused by misspelling/ wrong methods... etc and compilererrors caused by trying to implement new methods
So we miss a method that tells us whether the compileerror is caused by a missing method or something else, or a method that gives us the location/ name of the class used, so we can check if the method is already defined etc. 
We could check the strings for it anyhow, you said you check if you can do anything about that
Hope that's clearer now?

**Comment by bendisposto** [comment] 2016-07-03 13:27
I think you do not have to differentiate between "does not compile because the method is missing" and "does not compile for whatever other reason". If it does not compile, the user can proceed. If the problem is outside the code the user has to revert at a later point in time.

**Comment by bendisposto** [comment] 2016-10-07 12:28
won't fix (type of error can be figured out in client code)

**Closed as completed by bendisposto** 2016-10-07 12:28 UTC
